### ISSUE TITLE
Remove inactivity weeklys

### ISSUE THREAD

**Issue by matheusazzi** [matheusazzi/meet-weekly#61]

**Comment by mkautzmann** [comment]
:+1: 

There are some inactive weeklys indeed.

PS: WOW! There are more weeklys here now than I have the time to read, hahaha.

**Comment by matheusazzi** [comment]
Addressed here: https://github.com/matheusazzi/meet-weekly/commit/7291374475dc3f488a21a640c265844e3d886bb0
