### ISSUE TITLE
Better organization

### ISSUE THREAD

**Issue by mkautzmann** [matheusazzi/meet-weekly#77]
The list is big!

Maybe we can discuss ways to improve organization. I can think of a few possibilities:

Group by:

- Topics (database, back-end, front-end, etc)

**or**

- Languages (JS, Elixir, Ruby, etc)

**Comment by matheusazzi** [comment]
@mkautzmann 

Hey nice catch, I think by Topic is better but we can even have sub topics that can be the languages if the weekly is that specific.

Something like:

### Front-end
- ...
- ...

##### CSS
- ...
- ... 

##### Javascript
- ...
- ... 

### Databases
- ...

##### MongoDB
- ...
- ...

**Comment by matheusazzi** [comment]
Addressed here: https://github.com/matheusazzi/meet-weekly/commit/7291374475dc3f488a21a640c265844e3d886bb0
